version: '3.5'
services:

   mysql-manager:
     image: mysql/mysql-cluster:8.0
     container_name: manager
     networks:
      static_ip:
        ipv4_address: 198.168.0.2
     restart:  always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndb_mgmd

       
   data-node-1:
     image: mysql/mysql-cluster:8.0
     container_name: datanode1
     networks:
      static_ip:
        ipv4_address: 198.168.0.3
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndbd

   node_data_2:
     image: mysql/mysql-cluster:8.0
     container_name: datanode2
     networks:
      static_ip:
        ipv4_address: 198.168.0.4
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
     command: ndbd

   mysql_server_1:
     image: mysql/mysql-cluster:8.0
     container_name: mysqlserver1
     environment: 
       - "MYSQL_ROOT_PASSWORD=mypass"
     networks:
      static_ip:
        ipv4_address: 198.168.0.9
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     command: mysqld
     ports:
       - 5000:3306

   mysql_server_2:
     image: mysql/mysql-cluster:8.0
     container_name: mysqlserver2
     environment: 
       - "MYSQL_ROOT_PASSWORD=mypass"
     networks:
      static_ip:
        ipv4_address: 198.168.0.10
     restart:      always
     volumes:
       - ./cnf/my.cnf:/etc/my.cnf
       - ./cnf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     command: mysqld
     ports:
       - 5001:3306

networks:
  static_ip:
    name: my_network
    ipam:
      driver: default
      config:
        - subnet: 198.168.0.0/16
